# Generated by Django 4.2.7 on 2023-11-15 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='age',
            new_name='year',
        ),
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='sdsd', upload_to=''),
            preserve_default=False,
        ),
    ]
